name: ofm-infra

services:
  nats:
    image: nats:2.12.4-alpine
    container_name: ofm-nats
    restart: unless-stopped
    mem_limit: 256m
    cpus: "0.50"
    command:
      - "-js"
      - "-m"
      - "8222"
      - "-sd"
      - "/data/jetstream"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats_data:/data/jetstream

volumes:
  nats_data:
