services:
  grpc-docs-generate:
    image: gendocu/grpc-docs
    container_name: ofm-grpc-docs-generate
    mem_limit: 256m
    cpus: "0.25"
    volumes:
      - ../ofm-common/proto:/input:ro
      - ../ofm-docs/grpc:/output

  grpc-docs-preview:
    image: nginx:alpine
    container_name: ofm-grpc-docs-preview
    restart: unless-stopped
    mem_limit: 128m
    cpus: "0.25"
    ports:
      - "8083:80"
    volumes:
      - ../ofm-docs/grpc/build:/usr/share/nginx/html:ro
