services:
  asyncapi-validate:
    image: asyncapi/cli:latest
    container_name: ofm-asyncapi-validate
    working_dir: /workspace
    user: root
    mem_limit: 256m
    cpus: "0.25"
    environment:
      SUPPRESS_NO_CONFIG_WARNING: "true"
    volumes:
      - ../:/workspace
    command:
      - validate
      - /workspace/ofm-docs/asyncapi/nats-asyncapi.yaml

  asyncapi-preview:
    image: asyncapi/cli:latest
    container_name: ofm-asyncapi-preview
    restart: unless-stopped
    working_dir: /workspace
    user: root
    mem_limit: 512m
    cpus: "0.25"
    environment:
      SUPPRESS_NO_CONFIG_WARNING: "true"
    ports:
      - "8085:8085"
    volumes:
      - ../:/workspace
    command:
      - start
      - preview
      - /workspace/ofm-docs/asyncapi/nats-asyncapi.yaml
      - -p
      - "8085"
      - -B
      - -l
