services:
  order-service-redis:
    image: redis:8-alpine
    container_name: ofm-order-service-redis
    restart: unless-stopped
    mem_limit: 256m
    cpus: "0.50"
    ports:
      - "6382:6379"
    volumes:
      - order_service_redis_data:/data

  order-service-yugabyte:
    image: yugabytedb/yugabyte:2025.2.2.2-b11
    container_name: ofm-order-service-yugabyte
    restart: unless-stopped
    mem_limit: 2g
    cpus: "2.00"
    command: ["bin/yugabyted", "start", "--daemon=false"]
    ports:
      - "5437:5433"
      - "7004:7000"
      - "9004:9000"
      - "15437:15433"
    volumes:
      - order_service_yugabyte_data:/home/yugabyte/var

  order-service-yugabyte-init:
    image: yugabytedb/yugabyte:2025.2.2.2-b11
    container_name: ofm-order-service-yugabyte-init
    depends_on:
      - order-service-yugabyte
    restart: "no"
    mem_limit: 256m
    cpus: "0.25"
    entrypoint: ["/bin/bash", "-lc", "bash /scripts/init-order-yugabyte.sh"]
    volumes:
      - ./scripts/init-order-yugabyte.sh:/scripts/init-order-yugabyte.sh:ro

volumes:
  order_service_redis_data:
  order_service_yugabyte_data:
