apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    orgId: 1
    url: clickhouse:9000
    version: 1
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      host: clickhouse
      username: admin
      port: 9000
      protocol: native
      secure: false
      defaultDatabase: default
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
