{{- $secrets := default dict .Values._secrets -}}
{{- $monolith := default dict $secrets.monolith -}}
{{- if $monolith.rateLimiterBypassToken }}
apiVersion: v1
kind: Secret
metadata:
  name: ofm-monolith-rate-limit
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ofm.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ $monolith.rateLimiterBypassToken | quote }}
{{- end }}
