name=cdc-auth
connector.class=io.debezium.connector.postgresql.PostgresConnector
tasks.max=1
database.hostname=auth-service-postgres
database.port=5432
database.user=admin
database.password=admin
database.dbname=auth_service
topic.prefix=cdc.auth
slot.name=ofm_auth_cdc
publication.name=ofm_auth_cdc
plugin.name=pgoutput
table.include.list=public.outbox_events
snapshot.mode=never
