name=cdc-chat
connector.class=io.debezium.connector.postgresql.PostgresConnector
tasks.max=1
database.hostname=chat-service-postgres
database.port=5432
database.user=admin
database.password=admin
database.dbname=chat_service
topic.prefix=migration-chat
slot.name=ofm_chat_cdc
publication.name=ofm_chat_cdc
plugin.name=pgoutput
table.include.list=public.outbox_events
snapshot.mode=initial
