bootstrap.servers=kafka:9092
group.id=ofm-migration-connect
config.storage.topic=ofm-connect-configs
offset.storage.topic=ofm-connect-offsets
status.storage.topic=ofm-connect-status
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
plugin.path=/opt/kafka/connect,/opt/kafka/connect/debezium-connector-yugabytedb
rest.port=8083
