name=cdc-file
connector.class=io.debezium.connector.postgresql.PostgresConnector
tasks.max=1
database.hostname=file-service-postgres
database.port=5432
database.user=admin
database.password=admin
database.dbname=file_service
topic.prefix=migration-file
slot.name=ofm_file_cdc
publication.name=ofm_file_cdc
plugin.name=pgoutput
table.include.list=public.outbox_events
snapshot.mode=initial
