name=cdc-gig
connector.class=io.debezium.connector.yugabytedb.YugabyteDBgRPCConnector
tasks.max=1
database.hostname=gig-service-yugabyte
database.port=5433
database.master.addresses=gig-service-yugabyte:7100
database.user=yugabyte
database.password=yugabyte
database.dbname=gig_service
database.server.name=cdc.gig
database.streamid=823d6c161c74c78958497f6385f36eff
table.include.list=public.outbox_events
snapshot.mode=never
