name=cdc-order
connector.class=io.debezium.connector.postgresql.PostgresConnector
tasks.max=1
database.hostname=order-service-postgres
database.port=5432
database.user=admin
database.password=admin
database.dbname=order_service
topic.prefix=cdc.order
slot.name=ofm_order_cdc
publication.name=ofm_order_cdc
plugin.name=pgoutput
table.include.list=public.outbox_events
snapshot.mode=never
