name=cdc-order-saga
connector.class=io.debezium.connector.postgresql.PostgresConnector
tasks.max=1
database.hostname=order-saga-service-postgres
database.port=5432
database.user=admin
database.password=admin
database.dbname=order_saga
topic.prefix=migration-order-saga
slot.name=ofm_order_saga_cdc
publication.name=ofm_order_saga_cdc
plugin.name=pgoutput
table.include.list=public.outbox_events
snapshot.mode=initial
