name=cdc-order
connector.class=io.debezium.connector.yugabytedb.YugabyteDBgRPCConnector
tasks.max=1
database.hostname=order-service-yugabyte
database.port=5433
database.master.addresses=order-service-yugabyte:7100
database.user=yugabyte
database.password=yugabyte
database.dbname=order_service
database.server.name=cdc.order
database.streamid=d924bfd8bfbbac98384f8ac9239b2553
table.include.list=public.outbox_events
snapshot.mode=never
