name=cdc-payment
connector.class=io.debezium.connector.postgresql.PostgresConnector
tasks.max=1
database.hostname=payment-service-postgres
database.port=5432
database.user=admin
database.password=admin
database.dbname=payment_service
topic.prefix=cdc.payment
slot.name=ofm_payment_cdc
publication.name=ofm_payment_cdc
plugin.name=pgoutput
table.include.list=public.outbox_events
snapshot.mode=never
