name=cdc-payment
connector.class=io.debezium.connector.yugabytedb.YugabyteDBgRPCConnector
tasks.max=1
database.hostname=payment-service-yugabyte
database.port=5433
database.master.addresses=payment-service-yugabyte:7100
database.user=yugabyte
database.password=yugabyte
database.dbname=payment_service
database.server.name=cdc.payment
database.streamid=377c82362a68e08fbb46bf5fe5df690c
table.include.list=public.outbox_events
snapshot.mode=never
