name=cdc-registration-saga
connector.class=io.debezium.connector.postgresql.PostgresConnector
tasks.max=1
database.hostname=registration-saga-service-postgres
database.port=5432
database.user=admin
database.password=admin
database.dbname=registration_saga
topic.prefix=migration-registration-saga
slot.name=ofm_registration_saga_cdc
publication.name=ofm_registration_saga_cdc
plugin.name=pgoutput
table.include.list=public.outbox_events
snapshot.mode=initial
