name=cdc-review
connector.class=io.debezium.connector.yugabytedb.YugabyteDBgRPCConnector
tasks.max=1
database.hostname=review-service-yugabyte
database.port=5433
database.master.addresses=review-service-yugabyte:7100
database.user=yugabyte
database.password=yugabyte
database.dbname=review_service
database.server.name=cdc.review
database.streamid=b941c51a8823dbab694da0c7787d5790
table.include.list=public.outbox_events
snapshot.mode=never
