name=cdc-user
connector.class=io.debezium.connector.yugabytedb.YugabyteDBgRPCConnector
tasks.max=1
database.hostname=user-service-yugabyte
database.port=5433
database.master.addresses=user-service-yugabyte:7100
database.user=yugabyte
database.password=yugabyte
database.dbname=user_service
database.server.name=cdc.user
database.streamid=180b38ed35d5d5a5344661db8944b435
table.include.list=public.outbox_events
snapshot.mode=never
