name=cdc-user
connector.class=io.debezium.connector.postgresql.PostgresConnector
tasks.max=1
database.hostname=user-service-postgres
database.port=5432
database.user=admin
database.password=admin
database.dbname=user_service
topic.prefix=cdc.user
slot.name=ofm_user_cdc
publication.name=ofm_user_cdc
plugin.name=pgoutput
table.include.list=public.outbox_events
snapshot.mode=never
