name=scylla-cdc
bootstrap.servers=kafka:9092
connector.class=com.scylladb.cdc.debezium.connector.ScyllaConnector
key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
tasks.max=1
offset.flush.interval.ms=1000
offset.storage.file.filename=/tmp/connect.offsets
config.storage.file.filename=/tmp/connect.configs
status.storage.file.filename=/tmp/connect.status
plugin.path=/opt/kafka/connect
plugin.discovery=hybrid_warn
