bootstrap.servers=kafka:9092
group.id=ofm-migration-scylla-connect
config.storage.topic=ofm-scylla-connect-configs
offset.storage.topic=ofm-scylla-connect-offsets
status.storage.topic=ofm-scylla-connect-status
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
plugin.path=/opt/kafka/connect
plugin.discovery=hybrid_warn
rest.port=8083
